# Generated by Django 4.2.7 on 2025-01-19 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 19, 15, 36, 29, 605057, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='marriage',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
