# Generated by Django 4.2.7 on 2025-01-19 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_manufacture_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 19, 15, 37, 20, 776448, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата создания'),
        ),
    ]
