# Generated by Django 4.2.7 on 2024-11-19 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_manufacture_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 20, 46, 4, 707732, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
