# Generated by Django 4.2.7 on 2024-12-04 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_manufacture_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 0, 17, 55, 959109, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
